### ISSUE TITLE
Silently failing on upload/publish

### ISSUE THREAD

**Issue by lloydwheeler** [Cloudhuset/Zendesk-Guide-Pusher-Boilerplate#1]
Hi

Been using this plugin for the last few days (thanks!) but am running into intermittent issues with upload and publish. Sometimes the plugin will report successful publishing of the theme without the changes being reflected in Zendesk.

I assumed this would be either the CSRF token or cookie expiring but I'm still able to use the `gulp download` command without any issues, which suggests it's not an issue with the configuration. I've also looked briefly into the source code and it returns a 200 response.

Is there a request limit of some kind with the Zendesk API that could be causing this?

Cheers

**Comment by lloydwheeler** [comment]
Managed to work out the issue - when a template has a syntax error you'll get a successful publish from the plugin however Zendesk won't publish changes. Is there any easy way to respond with this kind of error in the response code?

**Comment by Herlevsen** [comment]
Hi @lloydwheeler 

I'm not 100% certain, but i seem to remember that Zendesk responds the same way, whether there is an error or not. I think it's something that we should look into though.

Would you mind creating an issue on the Zendesk-Guide-Pusher repository? If we discover that there is no way to tell if the push was successful or not, then we should at least have a notice in the documentation.

**Comment by lloydwheeler** [comment]
Thought I'd created this in the zendesk-guide-pusher repo! I'll close this one and create an issue there.

Thanks 👍
